#!/bin/bash
export TIMEFORMAT='%2Rs (%P%% CPU)'

runtest() {
  expect=$1
  shift
  printf "# Running test expecting $expect: %40s\n" "$*"
  eval time $@
  ret=$?
  if [ $ret != $expect ]; then
	echo  "#### !!!! Wrong return value $ret != $expect"
  fi
  sync
}

echo "# pdsync sync test"
runtest 1 ./pdsync -P --stats --threads=32 --hard-links --sparse --archive --delete dsync-test dsync-target
echo "# pdsync verify test. No output."
runtest 0 ./pdsync -P -i --stats --threads=32 --hard-links --sparse --archive --delete dsync-test dsync-target
echo "# rsync verify test. No output."
runtest 0 rsync --archive --hard-links --sparse -i --delete dsync-test/. dsync-target/.
echo "# pdsync --reflink test"
mkdir -vp dsync-target/reflink
runtest 1 ./pdsync -P --stats --threads=32 --hard-links --sparse --archive --delete dsync-target dsync-target/reflink
echo "# pdsync delete test"
runtest 1 ./pdsync -P --stats  --threads=32 --archive --delete dsync-test/emptydir dsync-target
echo "# rsync sync time test. No output."
runtest 0 rsync --archive --hard-links --delete dsync-test/. dsync-target/.
echo "# rsync delete test. No output."
runtest 0 rsync --archive --delete dsync-test/emptydir/. dsync-target/.
