#!/bin/bash
export TIMEFORMAT='%2Rs (%P%% CPU)'
threads=32
pdsync_args="--stats --threads=$threads --hard-links --sparse --archive --delete"
#pdsync_args="--stats --io_uring --threads=$threads --hard-links --sparse --archive --delete"

runtest() {
  expect=$1
  shift
  printf "# Running test expecting $expect: %40s\n" "$*"
  eval time $@
  ret=$?
  if [ $ret != $expect ]; then
	echo  "#### !!!! Wrong return value $ret != $expect. Exiting"
	exit 1
  fi
  if [ $ret -ge 10 ]; then
 	echo "#### CRASH. exiting"
        exit 1
  fi
  echo "### Finished ret=$ret. syncing."
  sync
}


echo "# Clearing dsync-target"
mkdir -p dsync-target/removeme
runtest 1 ./pdsync  $pdsync_args dsync-test/emptydir dsync-target

echo "# hard link tests"
runtest 1 ./pdsync -i --stats $pdsync_args dsync-test/hardlinks1 dsync-target
runtest 0 ./pdsync -i --stats $pdsync_args dsync-test/hardlinks1 dsync-target
runtest 2 ./pdsync -i --archive dsync-test/hardlinks2 dsync-target
runtest 1 ./pdsync -i $pdsync_args dsync-test/hardlinks2 dsync-target

echo "# short sanity tests"
touch dsync-target/removeme
runtest 1 ./pdsync -i $pdsync_args dsync-test/dir-is-in-the-way dsync-target
runtest 2 ./pdsync -i --archive dsync-test/symlinks dsync-target
runtest 1 ./pdsync -i $pdsync_args dsync-test/symlinks dsync-target
runtest 1 ./pdsync -i --dry-run $pdsync_args dsync-test/dir-is-in-the-way dsync-target > dryrun-output.txt

echo "# pdsync linux source test"
runtest 1 ./pdsync $pdsync_args dsync-test/linux-* dsync-target
echo "# pdsync verify. No output."
runtest 0 ./pdsync -i $pdsync_args dsync-test/linux-* dsync-target
echo "# rsync verify. No output."
runtest 0 rsync -i --archive --hard-links --delete dsync-test/linux-*/. dsync-target/.
echo "# pdsync delete test"
runtest 1 ./pdsync $pdsync_args dsync-test/emptydir/. dsync-target/.

echo "# pdsync long test."
runtest 1 ./pdsync -P $pdsync_args dsync-test dsync-target
echo "# pdsync verify test. No output."
runtest 0 ./pdsync -P -i $pdsync_args dsync-test dsync-target
echo "# rsync verify test. No output."
runtest 0 rsync --archive --hard-links --sparse -i --delete dsync-test/. dsync-target/.
echo "# pdsync --reflink --sync-tag test"
mkdir -vp dsync-target/reflink
runtest 1 ./pdsync -P $pdsync_args --reflink --sync-tag=testitag dsync-target dsync-target/reflink
echo "# pdsync --sync-tag test: should do nothing"
runtest 0 ./pdsync -P -i $pdsync_args --reflink --sync-tag=testitag dsync-target dsync-target/reflink

echo "# pdsync symlink delete test. No output."
runtest 1 ./pdsync $pdsync_args dsync-test/symlinks/. dsync-target/.

echo "# pdsync delete test"
runtest 1 ./pdsync -P $pdsync_args dsync-test/emptydir dsync-target
exit 0
echo "# rsync sync time test. No output."
runtest 0 rsync --archive --hard-links --delete dsync-test/. dsync-target/.
echo "# rsync delete test. No output."
runtest 0 rsync --archive --delete dsync-test/emptydir/. dsync-target/.
